kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: My brother name is 
      value: 'Raj'
    - name: My sis name is 
      value: 'Bhavs'
      