kind: Pod
apiVersion: v1 
metadata: 
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
        cpu: "100m"
        memory: "128Mi"
      # hard limit
      limits:
        cpu: "200m"
        memory: "200Mi"