apiVersion: v1 
kind: Pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom: 
        configMapKeyRef:
          name: configurations
          key: course
    - name: trainer
      valueFrom: 
        configMapKeyRef:
          name: configurations
          key: trainer
    - name: github
      valueFrom: 
        configMapKeyRef:
          name: configurations
          key: github
