kind: Secret
apiVersion: v1 
metadata: 
  name: pod-secret
data:
  username: "YWRtaW4K"
  # This is the encoded one.. 
  # command: echo admin | base64  ==  It will gives the encoded value of admin
  # We give encoded value here
  password: "YWRtaW4xMjMK"